package com.example.crypto4view;
import android.app.*;import android.content.*;import android.os.*;import java.io.*;import java.net.*;import org.json.*;
public class PriceAlertService extends Service{
 Handler h;final Runnable r=()->{check();h.postDelayed(r,30000);};
 public void onCreate(){super.onCreate();NotificationManager n=getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel("alerts","Crypto alerts",NotificationManager.IMPORTANCE_DEFAULT));startForeground(7,new Notification.Builder(this,"alerts").setContentTitle("Crypto 4View").setContentText("Price monitoring is running").setSmallIcon(android.R.drawable.ic_dialog_info).setOngoing(true).build());h=new Handler(Looper.getMainLooper());h.post(r);}
 void check(){new Thread(()->{String[] ss={"LTCUSDT","HMSTRUSDT","SPCXBUSDT"};for(String s:ss)try{URL u=new URL("https://api.binance.com/api/v3/ticker/price?symbol="+s);HttpURLConnection c=(HttpURLConnection)u.openConnection();BufferedReader b=new BufferedReader(new InputStreamReader(c.getInputStream()));String q="",x;while((x=b.readLine())!=null)q+=x;double p=Double.parseDouble(new JSONObject(q).getString("price"));levels(s,p);}catch(Exception e){}}).start();}
 void levels(String s,double p){String id=s.toLowerCase();android.content.SharedPreferences a=getSharedPreferences("alerts",0);double prev=a.getFloat("prev_"+id,(float)p);try{String up=a.getString("upper_"+id,""),lo=a.getString("lower_"+id,"");if(!up.isEmpty()&&prev<Double.parseDouble(up)&&p>=Double.parseDouble(up))push(s,"Upper crossed: "+p);if(!lo.isEmpty()&&prev>Double.parseDouble(lo)&&p<=Double.parseDouble(lo))push(s,"Lower crossed: "+p);}catch(Exception e){}a.edit().putFloat("prev_"+id,(float)p).apply();}
 void push(String t,String b){getSystemService(NotificationManager.class).notify((int)(System.currentTimeMillis()%100000),new Notification.Builder(this,"alerts").setContentTitle(t).setContentText(b).setSmallIcon(android.R.drawable.ic_dialog_alert).setAutoCancel(true).build());}
 public int onStartCommand(Intent i,int f,int id){return START_STICKY;}public void onDestroy(){if(h!=null)h.removeCallbacks(r);super.onDestroy();}public android.os.IBinder onBind(Intent i){return null;}
}